### ISSUE TITLE
The currency formatting must be culture invariant

### ISSUE THREAD

**Issue by mgesing** [amzn/amazon-pay-sdk-csharp#12]
Otherwise methods like [SetOrderReferenceDetails](https://github.com/amzn/amazon-pay-sdk-csharp/blob/master/AmazonPay/Client.cs#L425) produces an error InvalidParameterValue, "The Value 'x' is invalid for the Parameter 'Amount'". See [pull request](https://github.com/amzn/amazon-pay-sdk-csharp/pull/5/commits/1ed7fa92098f5a2195228efae5a062de38427410).

**Comment by bjguillot** [comment]
We are actively working on a change very similar to pull request #5 to fix the currency issues when working in non-US cultures.

**Comment by mgesing** [comment]
Has been solved by SDK 3.1.1. Thank you.
