### ISSUE TITLE
Optional client configuration variables throw exception

### ISSUE THREAD

**Issue by jeremy-loffredo** [amzn/amazon-pay-sdk-csharp#2]
application_name and application_version are considered optional per readme. If these values are not provided, they default to null.

SetUserAgentHeader throws an exception when attempting to work with the null value as a string.

**Comment by shrakuma** [comment]
Hi
Thank you for finding the bug and bringing it to my attention. I have fixed the issue in the latest upload to the DoDo branch. please check and let me know if everything works okay and also feel free to let me know anytime if you see any issues. I will fix them ASAP

**Comment by jeremy-loffredo** [comment]
Verified!
