### ISSUE TITLE
This operation could not supported by .NET Core 2.0

### ISSUE THREAD

**Issue by ilgol** [amzn/amazon-pay-sdk-csharp#21]
https://github.com/amzn/amazon-pay-sdk-csharp/blob/ef8b9ec5d40887b0dc7423216b4724d2f45cebbb/AmazonPay/Signature.cs#L112

Have You any plans to resolve this issue?
Thank You!

**Comment by bjguillot** [comment]
I am closing this as a duplicate for https://github.com/amzn/amazon-pay-sdk-csharp/issues/20

Can you please go to that link, and reply with the answer to the following question:

As a user of the SDK, can you provide some feedback on how .NET Core or .NET Standard would help in your environment? Knowing how this would help our customers can provide us with valuable insights. Thanks in advance for any feedback.
