### ISSUE TITLE
Nuget assembly strong name missing

### ISSUE THREAD

**Issue by four-bytes-robby** [amzn/amazon-pay-sdk-csharp#22]
Current version (3.5.0) of the nuget package has no strong name support as well as 3.4.3.2.

Version 3.4.3.1 has a strong name/is signed.

When a project is depending on the nuget package which is signed amazon pay will not work.

It would be amazing if this could be fixed.

**Comment by bjguillot** [comment]
Thank you for bringing this to our attention.  We are looking into this.

**Comment by four-bytes-robby** [comment]
No update so far?
What about the PSD2 update? Will this happen to this sdk as well?
Dead line is 14th of September, Amazon send us an information about the update which should be integrated already June 30th.

**Comment by bjguillot** [comment]
We're doing internal testing on the 3.5.1 release right now.  One of my teammates will be posting it once all the tests pass.

For PSD2-related changes, we call that SCA: Strong Customer Authentication.  The 3.5.0 release added new setters on the ConfirmOrderReference method.  The 3.5.1 release will add a getter on GetOrderReferenceDetails that is also needed for SCA, though you can always access any new fields from responses that don't yet have getters by using this SDK's Dictionary response.  Those attribute names are mentioned in the SCA Integration Guide (For others reading this comment, SCA changes are related to merchants in Europe and UK regions only.)

**Comment by bjguillot** [comment]
The 3.5.1 release is now published to GitHub and NuGet:
* https://github.com/amzn/amazon-pay-sdk-csharp/releases/tag/3.5.1
* https://www.nuget.org/packages/AmazonPay/3.5.1

If this fixes your problem, please close the issue.

**Comment by bjguillot** [comment]
Haven't heard anything in a few weeks, so assuming this issue was resolved in the 3.5.1 release.

**Comment by four-bytes-robby** [comment]
Will confirm if it has been solved later. Other things were in focus and I may have missed the github notification about the answer.

**Comment by four-bytes-robby** [comment]
Obviously seems to work :)
