### ISSUE TITLE
Is it a typo with method name WithAmazonBillingreementId in class ConfirmBillingAgreementRequest?

### ISSUE THREAD

**Issue by Tharnadar** [amzn/amazon-pay-sdk-csharp#23]
The correct method name should be WithAmazonBillingAgreementId ?

**Comment by islandskater43** [comment]
Absolutely @Tharnadar - great catch. Feel free to submit a backward compatible PR to address, or we'll address in our next update pass!

**Comment by bjguillot** [comment]
This was addressed in the 3.5.1 release.  The original typo was left in place with a deprecation tag so that we won't break any existing usage, and a new method with added with correct name.
