### ISSUE TITLE
v3.5.1 Newtonsoft.Json version discrepancy

### ISSUE THREAD

**Issue by stemyers** [amzn/amazon-pay-sdk-csharp#24]
Hi,

**Issue:**
In release v3.5.1 there is a discrepancy with the version of Newtonsoft.Json referenced by the project and the minimum version specified in the nuspec. The library is compiled against v12.0.2 and the nuspec specifies v11.0.2 as the minimum supported version.

**Effect:**
When installing the nuget package, the SDK package installs successfully when v11.0.2 of Newtonsoft.Json is installed on the project, however causes a System.IO.FileLoadException runtime error due to the compiled dependency on v12.0.2

**Comment by bjguillot** [comment]
Thanks for bringing this to our attention.  We will reply back with more information soon.

**Comment by rubberfashion** [comment]
I have the same issue. 

Line: this.json = ResponseParser.ToJson(xml);

An unhandled exception of type 'System.IO.FileLoadException' occurred in AmazonPay.dll

Additional information: Die Datei oder Assembly "Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" oder eine Abhängigkeit davon wurde nicht gefunden. 

It is not possible to make any call. Every time i got this error. Also other versions do not work.

**Comment by OhkaBaka** [comment]
I've just tested 3.5.1.1 and the proper version of Newtonsoft.Json is attached when installing.
