### ISSUE TITLE
Optional configuration throws exception if null - SetOrderReferenceDetails

### ISSUE THREAD

**Issue by jeremy-loffredo** [amzn/amazon-pay-sdk-csharp#3]
When calling SetOrderReferenceDetails, platform_id must be set or a null value exception occurs.

**Comment by shrakuma** [comment]
I have made this fix too in the latest update. Thanks again for bringing it to my attention.

**Comment by jeremy-loffredo** [comment]
This did not work. Please see pull request.

**Comment by shrakuma** [comment]
fixed issue
